/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author somala
 */
public class GUI_MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MenuAdmin
     */
    public GUI_MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDataBuku = new javax.swing.JButton();
        btnDataMember = new javax.swing.JButton();
        btnDataPeminjaman = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERPUSTAKAAN ITATS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Admin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 49, -1, -1));

        btnDataBuku.setBackground(new java.awt.Color(255, 228, 196));
        btnDataBuku.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnDataBuku.setText("Data Buku");
        btnDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBukuActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, 35));

        btnDataMember.setBackground(new java.awt.Color(255, 228, 196));
        btnDataMember.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnDataMember.setText("Data Member");
        btnDataMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, 36));

        btnDataPeminjaman.setBackground(new java.awt.Color(255, 228, 196));
        btnDataPeminjaman.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnDataPeminjaman.setText("Data Peminjaman");
        btnDataPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPeminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, 35));

        btnExit.setBackground(new java.awt.Color(255, 239, 219));
        btnExit.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnExit.setText("Logout");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4-cara-paling-mudah-dalam-menjilid-buku-sendiri.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -13, 450, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new GUI_MenuAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBukuActionPerformed
        try {
            // TODO add your handling code here:
            new GUI_DataBuku().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnDataBukuActionPerformed

    private void btnDataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMemberActionPerformed
        try {
            // TODO add your handling code here:
            new GUI_DataMember().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnDataMemberActionPerformed

    private void btnDataPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPeminjamanActionPerformed
        try {
            // TODO add your handling code here:
            new GUI_DataPeminjaman().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnDataPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataBuku;
    private javax.swing.JButton btnDataMember;
    private javax.swing.JButton btnDataPeminjaman;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
