package View;

import Controller.Controller_Peminjaman;
import Controller.Controller_Buku;
import Controller.Controller_Admin;
import Controller.Controller_Member;
import Model.Detail_Peminjaman;
import Model.Admin;
import Model.Buku;
import Model.Member;
import Model.Peminjaman;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;

public class GUI_PinjamBuku extends javax.swing.JFrame {

    private Controller_Peminjaman controller_peminjaman;
    private Controller_Buku controller_buku;
    private Controller_Admin controller_admin;
    private Controller_Member controller_member;
    private ArrayList<Peminjaman> arrPeminjaman;
    private ArrayList<Detail_Peminjaman> arrKeranjang;

    /**
     * Creates new form GUI_PinjamBuku
     */
    public GUI_PinjamBuku() throws SQLException {
        initComponents();
        this.arrPeminjaman = new ArrayList<>();
        this.arrKeranjang = new ArrayList<>();
        this.controller_peminjaman = new Controller_Peminjaman();
        this.controller_buku = new Controller_Buku();
        this.controller_admin = new Controller_Admin();
        this.controller_member = new Controller_Member();
        this.showComboBoxAdmin();
        this.showComboBoxMember();
        this.showComboBoxBuku();
        this.showTablePeminjaman();

        this.tblBuku.setModel(this.controller_buku.viewTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbId_Admin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbIdMember = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeminjam = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        cbIdBuku = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfTglPinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("PEMINJAMAN BUKU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 53, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama Admin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 109, -1, -1));

        cbId_Admin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbId_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 107, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Member");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Buku");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, -1, -1));

        cbIdMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbIdMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 146, 210, -1));

        btnAdd.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 180, -1, -1));

        btnBack.setFont(new java.awt.Font("Tw Cen MT", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 568, 69, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tabel Data Peminjam");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, -1, -1));

        tblPeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeminjam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 324, 319, 226));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tabel Data Buku");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 146, -1, -1));

        btnSave.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 568, -1, -1));

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblBuku);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 180, 500, 370));

        cbIdBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdBukuActionPerformed(evt);
            }
        });
        getContentPane().add(cbIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 182, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tgl Pinjam");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, -1));
        getContentPane().add(tfTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 222, 210, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books-1845614_1280.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void showTablePeminjaman() throws SQLException {
        DefaultTableModel dtmPeminjaman = new DefaultTableModel(new String[]{"ID Buku", "Judul Buku"}, 0);
        dtmPeminjaman.setRowCount(0);

        for (Detail_Peminjaman dp : this.arrKeranjang) {
            dtmPeminjaman.addRow(new String[]{dp.getBuku().getId_Buku().toString(), dp.getBuku().getJudul_Buku()});

        }
        this.tblPeminjam.setModel(dtmPeminjaman);
    }

    public void setTabelModel() throws SQLException {
        this.tblBuku.setModel(this.controller_buku.viewTabel());
    }

    public void showComboBoxAdmin() throws SQLException {
        DefaultComboBoxModel dcbmAdmin = new DefaultComboBoxModel();

        for (Admin a : this.controller_admin.getDataAdmin()) {
            dcbmAdmin.addElement(a.getNama());
        }
        this.cbId_Admin.setModel(dcbmAdmin);
    }

    public void showComboBoxMember() throws SQLException {
        DefaultComboBoxModel dcbmMember = new DefaultComboBoxModel();

        for (Member m : this.controller_member.getDataMember()) {
            dcbmMember.addElement(m.getNama());
        }
        this.cbIdMember.setModel(dcbmMember);
    }

    public void showComboBoxBuku() throws SQLException {
        DefaultComboBoxModel dcbmBuku = new DefaultComboBoxModel();

        for (Buku b : this.controller_buku.getDataBuku()) {
            dcbmBuku.addElement(b.getJudul_Buku());
        }
        this.cbIdBuku.setModel(dcbmBuku);
    }

    private boolean cekSemuaTextKosong() {
        boolean textKosong = false;
        if (this.tfTglPinjam.getText().isEmpty()) {
            textKosong = true;
        }
        return textKosong;
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new GUI_MenuMember().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdBukuActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (cekSemuaTextKosong()) {
            JOptionPane.showMessageDialog(null, "Isi Semua Kolom Isian Terlebih Dahulu",
                    "Gagal Insert", WARNING_MESSAGE);
        } else {
            Detail_Peminjaman dp = new Detail_Peminjaman();
            try {

                dp.setBuku(this.controller_buku.getDataBuku().get(this.cbIdBuku.getSelectedIndex()));
               
                this.arrKeranjang.add(dp);
                this.showTablePeminjaman();
                JOptionPane.showMessageDialog(null, "Sukses");

            } catch (SQLException err) {
                System.out.println(err);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Peminjaman peminjaman = new Peminjaman();
        try {
            peminjaman.setAdmin(this.controller_admin.getDataAdmin().get(this.cbId_Admin.getSelectedIndex()));
            peminjaman.setMember(this.controller_member.getDataMember().get(this.cbIdMember.getSelectedIndex()));
            peminjaman.setBuku(this.controller_buku.getDataBuku().get(this.cbIdBuku.getSelectedIndex()));
            peminjaman.setTanggal_Pinjam(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTglPinjam.getText()));
            peminjaman.setArrDetail_Peminjaman(this.arrKeranjang);

            //this.controller_peminjaman.getDataPeminjaman();
            this.controller_peminjaman.insertPeminjaman(peminjaman);
            this.showTablePeminjaman();
            this.arrKeranjang = new ArrayList<>();
            this.showComboBoxAdmin();
            this.showComboBoxMember();
            this.showComboBoxBuku();
            JOptionPane.showMessageDialog(null, "Pinjam Buku Sukses");

        } catch (SQLException | ParseException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_PinjamBuku().setVisible(true);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(GUI_PinjamBuku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbIdBuku;
    private javax.swing.JComboBox<String> cbIdMember;
    private javax.swing.JComboBox<String> cbId_Admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTable tblPeminjam;
    private javax.swing.JTextField tfTglPinjam;
    // End of variables declaration//GEN-END:variables
}
