package View;

import Controller.Controller_Member;
import Controller.Controller_Global;
import Model.Member;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

public class GUI_LoginMember extends javax.swing.JFrame {

    Controller_Member controller_member;
    Controller_Global controller_global;

    /**
     * Creates new form GUI_LoginMember
     */
    public GUI_LoginMember() {
        initComponents();
        this.controller_member = new Controller_Member();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIdMember = new javax.swing.JTextField();
        pfPasswordMember = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegis = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login Member");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Member");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 133, -1, -1));
        getContentPane().add(tfIdMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 85, 203, -1));

        pfPasswordMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordMemberActionPerformed(evt);
            }
        });
        getContentPane().add(pfPasswordMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 131, 203, -1));

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 169, -1, -1));

        btnRegis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegis.setText("Register");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 169, -1, -1));

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 169, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 2, 410, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pfPasswordMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordMemberActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        // TODO add your handling code here:
        new GUI_RegisMember().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegisActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new GUI_MenuAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private boolean cekSemuaTextKosong() {
        boolean textKosong = false;
        if (this.tfIdMember.getText().isEmpty()
                || this.pfPasswordMember.getText().isEmpty()) {
            textKosong = true;
        }
        return textKosong;
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        if (cekSemuaTextKosong()) {
            JOptionPane.showMessageDialog(null, "Masukkan ID dan Password Terlebih Dahulu",
                    "Gagal Login", WARNING_MESSAGE);
        } else {
            int id = Integer.parseInt(this.tfIdMember.getText());
            String pass = this.pfPasswordMember.getText();
            boolean loginValid = false;
            try {
                loginValid = validasiDataLogin(id, pass);
            } catch (SQLException ex) {
                Logger.getLogger(GUI_LoginMember.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (loginValid == true) {
                String password = this.pfPasswordMember.getText();
                try {
                    int kodeMember = this.controller_member.cariIdMember(password);
                    Controller_Global.Id_Member = kodeMember;
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_LoginMember.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    new GUI_PinjamBuku().setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_LoginMember.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Password Anda Salah");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean validasiDataLogin(int id_member, String password) throws SQLException {
        boolean loginValid = false;
        ArrayList<Member> arrMember = this.controller_member.getDataMember();
        for (int i = 0; i < arrMember.size(); i++) {
            if (id_member == arrMember.get(i).getId_Member() && password.equals(arrMember.get(i).getPassword())) {
                loginValid = true;
            }
        }
        return loginValid;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_LoginMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pfPasswordMember;
    private javax.swing.JTextField tfIdMember;
    // End of variables declaration//GEN-END:variables

}
