package View;

import Controller.Controller_Buku;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

public class GUI_DataBuku extends javax.swing.JFrame {

    Controller_Buku controller_buku;

    /**
     * Creates new form GUI_DataBuku
     */
    public GUI_DataBuku() throws SQLException {
        initComponents();
        this.controller_buku = new Controller_Buku();
        this.setTabelModel();
        this.kosong();

        this.tblBuku.setModel(this.controller_buku.viewTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfIdBuku = new javax.swing.JTextField();
        tfJudul = new javax.swing.JTextField();
        tfPengarang = new javax.swing.JTextField();
        tfTahun = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA BUKU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pengarang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 206, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tahun Terbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 255, -1, -1));

        tfIdBuku.setBackground(new java.awt.Color(255, 245, 238));
        tfIdBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdBukuActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 113, 230, -1));

        tfJudul.setBackground(new java.awt.Color(255, 245, 238));
        tfJudul.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 157, 230, -1));

        tfPengarang.setBackground(new java.awt.Color(255, 245, 238));
        tfPengarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 203, 230, -1));

        tfTahun.setBackground(new java.awt.Color(255, 245, 238));
        tfTahun.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 252, 230, -1));

        btnAdd.setBackground(new java.awt.Color(255, 245, 238));
        btnAdd.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 156, 80, -1));

        btnEdit.setBackground(new java.awt.Color(255, 245, 238));
        btnEdit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 202, 80, -1));

        btnDelete.setBackground(new java.awt.Color(255, 245, 238));
        btnDelete.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 156, 73, -1));

        btnClear.setBackground(new java.awt.Color(255, 245, 238));
        btnClear.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 202, 73, -1));

        tblBuku.setBackground(new java.awt.Color(255, 218, 185));
        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 314, 700, 268));

        btnBack.setBackground(new java.awt.Color(255, 245, 238));
        btnBack.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jaredd-craig-HH4WBGNyltc-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -6, 790, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public void kosong() {
        this.tfIdBuku.setText("");
        this.tfJudul.setText("");
        this.tfPengarang.setText("");
        this.tfTahun.setText("");
    }

    public void setTabelModel() throws SQLException {
        this.tblBuku.setModel(this.controller_buku.viewTabel());
    }

    private boolean cekSemuaTextKosong() {
        boolean textKosong = false;
        if (this.tfIdBuku.getText().isEmpty()
                || this.tfJudul.getText().isEmpty()
                || this.tfPengarang.getText().isEmpty()
                || this.tfTahun.getText().isEmpty()) {
            textKosong = true;
        }
        return textKosong;
    }


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new GUI_MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
//         TODO add your handling code here:
        if (cekSemuaTextKosong()) {
            JOptionPane.showMessageDialog(null, "Isi Semua Kolom Isian Terlebih Dahulu",
                    "Gagal Insert", WARNING_MESSAGE);
        } else {
            try {
                int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Input Buku?",
                        "Konfirmasi", OK_CANCEL_OPTION, QUESTION_MESSAGE);
                if (konfirmasi == 0) {
                    int id_buku = Integer.parseInt(this.tfIdBuku.getText());
                    String judul_buku = this.tfJudul.getText();
                    String pengarang = this.tfPengarang.getText();
                    int tahun_terbit = Integer.parseInt(this.tfTahun.getText());
                    this.controller_buku.insert(id_buku, judul_buku, pengarang, tahun_terbit);
                }
                this.setTabelModel();
                this.kosong();
                JOptionPane.showMessageDialog(null, "Input Data Buku Berhasil ");
            } catch (SQLException ex) {
                Logger.getLogger(GUI_DataBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (cekSemuaTextKosong()) {
            JOptionPane.showMessageDialog(null, "Pilih Baris Data Terlebih Dahulu",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int konfirmasi = JOptionPane.showConfirmDialog(null, "Data Akan Diupdate?",
                        "Konfirmasi", OK_CANCEL_OPTION, QUESTION_MESSAGE);
                if (konfirmasi == 0) {
                    //int baris = tblBuku.getSelectedRow();
                    if ("".equals(tfIdBuku.getText()) || "".equals(tfJudul.getText()) || "".equals(tfPengarang.getText()) || "".equals(tfTahun.getText())) {
                        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
                    }
                    int id_buku = Integer.parseInt(this.tfIdBuku.getText());
                    String judul_buku = this.tfJudul.getText();
                    String pengarang = this.tfPengarang.getText();
                    int tahun_terbit = Integer.parseInt(this.tfTahun.getText());
                    this.controller_buku.update(id_buku, judul_buku, pengarang, tahun_terbit);

                    this.setTabelModel();
                    this.kosong();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUI_DataBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (cekSemuaTextKosong()) {
            JOptionPane.showMessageDialog(null, "Pilih Baris Data Terlebih Dahulu",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int konfirmasi = JOptionPane.showConfirmDialog(null, "Data Akan Dihapus?",
                        "Konfirmasi", OK_CANCEL_OPTION, QUESTION_MESSAGE);
                if (konfirmasi == 0) {
                    int baris = tblBuku.getSelectedRow();
                    int id_buku = Integer.parseInt(tblBuku.getValueAt(baris, 0).toString());
                    this.controller_buku.delete(id_buku);

                    this.setTabelModel();
                    this.kosong();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(GUI_DataBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        try {
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin Ingin Hapus Semua Data?",
                    "Konfirmasi", OK_CANCEL_OPTION, QUESTION_MESSAGE);
            if (konfirmasi == 0) {
                this.controller_buku.clear();

                this.setTabelModel();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_DataBuku.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnClearActionPerformed

    private void tfIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdBukuActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        int baris = tblBuku.getSelectedRow();
        this.tfIdBuku.setText(tblBuku.getValueAt(baris, 0).toString());
        this.tfJudul.setText(tblBuku.getValueAt(baris, 1).toString());
        this.tfPengarang.setText(tblBuku.getValueAt(baris, 2).toString());
        this.tfTahun.setText(tblBuku.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tblBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_DataBuku().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_DataBuku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField tfIdBuku;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfPengarang;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
