package View;

import Controller.Controller_Peminjaman;
import Model.Detail_Peminjaman;
import Model.Peminjaman;
import database.Koneksi;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class GUI_DataPeminjaman extends javax.swing.JFrame {

    private Controller_Peminjaman controller_peminjaman;
    private ArrayList<Detail_Peminjaman> arrKeranjang;
    private Koneksi koneksi;

    /**
     * Creates new form GUI_DataPeminjaman
     */
    public GUI_DataPeminjaman() throws SQLException {
        initComponents();
        this.arrKeranjang = new ArrayList<>();
        this.controller_peminjaman = new Controller_Peminjaman();
        this.koneksi = new Koneksi();
        this.showTablePeminjam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();
        btnLihatDetail = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLihatDetail = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PEMINJAMAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        tfSearch.setBackground(new java.awt.Color(255, 245, 238));
        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 230, 22));

        btnSearch.setBackground(new java.awt.Color(255, 245, 238));
        btnSearch.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 94, -1, -1));

        tblPeminjaman.setBackground(new java.awt.Color(255, 218, 185));
        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 645, 200));

        btnLihatDetail.setBackground(new java.awt.Color(255, 245, 238));
        btnLihatDetail.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnLihatDetail.setText("Lihat Detail");
        btnLihatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnLihatDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 353, -1, -1));

        taLihatDetail.setBackground(new java.awt.Color(255, 228, 196));
        taLihatDetail.setColumns(20);
        taLihatDetail.setRows(5);
        jScrollPane2.setViewportView(taLihatDetail);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 394, 645, 206));

        btnBack.setBackground(new java.awt.Color(255, 245, 238));
        btnBack.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 618, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/janko-ferlic-sfL_QOnmy00-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, -3, 680, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void showTablePeminjam() throws SQLException {
        DefaultTableModel dtmPinjam = new DefaultTableModel(new String[]{"ID Peminjaman", "Admin", "Member", "Tanggal Pinjam"}, 0);
        dtmPinjam.setRowCount(0);

        for (Peminjaman dp : this.controller_peminjaman.getDataPeminjaman()) {
            dtmPinjam.addRow(new String[]{dp.getId_Peminjaman().toString(), dp.getAdmin().getNama(), 
                dp.getMember().getNama(), dp.getTanggal_Pinjam().toString()});
        }

        this.tblPeminjaman.setModel(dtmPinjam);
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new GUI_MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLihatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDetailActionPerformed
        // TODO add your handling code here:
        try {
            Peminjaman peminjaman = this.controller_peminjaman.getDataPeminjaman().get(this.tblPeminjaman.getSelectedRow());
            String teks = "" + "====================== MEMBER ======================" + "\n"
                    + "ID Member : " + peminjaman.getMember().getId_Member() + "\n"
                    + "Nama : " + peminjaman.getMember().getNama() + "\n"
                    + "Alamat : " + peminjaman.getMember().getAlamat() + "\n"
                    + "Jenis Kelamin : " + peminjaman.getMember().getJenis_Kelamin() + "\n"
                    + "Tanggal Lahir : " + new SimpleDateFormat("dd/MM/yyyy").format(peminjaman.getMember().getTanggal_Lahir()) + "\n"
                    + "No. Telp : " + peminjaman.getMember().getNo_Telp() + "\n\n"
                    + "======================= ADMIN ======================" + "\n"
                    + "ID Admin : " + peminjaman.getAdmin().getId_Admin() + "\n"
                    + "Nama : " + peminjaman.getAdmin().getNama() + "\n"
                    + "Alamat : " + peminjaman.getAdmin().getAlamat() + "\n"
                    + "Jenis Kelamin : " + peminjaman.getAdmin().getJenis_Kelamin() + "\n\n"
                    + "==================== PEMINJAMAN ====================" + "\n"
                    + "ID Peminjaman : " + peminjaman.getId_Peminjaman() + "\n"
                    + "Tanggal Peminjaman : " + new SimpleDateFormat("dd/MM/yyyy").format(peminjaman.getTanggal_Pinjam()) + "\n"
                    + "Peminjaman : " + "\n";
            ArrayList<Detail_Peminjaman> dp = peminjaman.getArrDetail_Peminjaman();
            for (int i = 0; i < dp.size(); i++) {
                teks += "\n" + (i + 1) + ". "
                        + "ID Buku          : " + dp.get(i).getPeminjaman().getBuku().getId_Buku() + "\n"
                        + "    Judul Buku    : " + dp.get(i).getPeminjaman().getBuku().getJudul_Buku() + "\n"
                        + "    Pengarang    : " + dp.get(i).getPeminjaman().getBuku().getPengarang() + "\n"
                        + "    Tahun Terbit : " + dp.get(i).getPeminjaman().getBuku().getTahun_Terbit();
            }

            this.taLihatDetail.setText(teks);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnLihatDetailActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            int id_peminjaman = Integer.parseInt(this.tfSearch.getText());
            this.controller_peminjaman.cariData(id_peminjaman);

            DefaultTableModel dtmPinjam = (DefaultTableModel) tblPeminjaman.getModel();
            tfSearch.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_DataPeminjaman().setVisible(true);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(GUI_DataPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLihatDetail;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taLihatDetail;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
