package View;

import Controller.Controller_Admin;
import Controller.Controller_Global;
import Model.Admin;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GUI_LoginAdmin extends javax.swing.JFrame {

    Controller_Admin controller_admin;
    Controller_Global controller_global;

    /**
     * Creates new form GUI_LoginAdmin
     */
    public GUI_LoginAdmin() throws SQLException {
        initComponents();
        this.controller_admin = new Controller_Admin();
        //this.showComboBoxAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pfPass = new javax.swing.JPasswordField();
        tfId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Admin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        pfPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(pfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 108, 156, -1));

        tfId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 68, 158, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -9, 400, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    public void showComboBoxAdmin() throws SQLException {
//        DefaultComboBoxModel dcbmAdmin = new DefaultComboBoxModel();
//
//        for (Admin a : this.controller_admin.getDataAdmin()) {
//            dcbmAdmin.addElement(a.getNama());
//        }
//        this.cbId.setModel(dcbmAdmin);
//    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new GUI_MenuAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(this.tfId.getText());
        String pass = this.pfPass.getText();
        boolean loginValid = false;
        try {
            loginValid = validasiDataLogin(id, pass);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (loginValid == true) {
            String password = this.pfPass.getText();
            try {
                int kodeAdmin = this.controller_admin.cariIdAdmin(password);
                Controller_Global.Id_Admin = kodeAdmin;
            } catch (SQLException ex) {
                Logger.getLogger(GUI_LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

            new GUI_MenuAdmin().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Password Anda Salah");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean validasiDataLogin(int id_admin, String password) throws SQLException {
        boolean loginValid = false;
        ArrayList<Admin> arrAdmin = this.controller_admin.getDataAdmin();
        for (int i = 0; i < arrAdmin.size(); i++) {
            if (id_admin == arrAdmin.get(i).getId_Admin() && password.equals(arrAdmin.get(i).getPassword())) {
                loginValid = true;
            }
        }
        return loginValid;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_LoginAdmin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables
}
